package com.kth.journal.domain;

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Embeddable;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;

@Embeddable
public class MessageId implements Serializable {

    @OneToMany
    @JoinColumn(name = "account_id")
    private Account account;

    // timestamp generated by the server
    private String timestamp;

    public MessageId() {
    }

    public MessageId(Account account, String timestamp) {
        this.account = account;
        this.timestamp = timestamp;
    }

    public Account getAccount() {
        return account;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        MessageId messageId = (MessageId) o;
        return Objects.equals(account, messageId.account) && Objects.equals(timestamp, messageId.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(account, timestamp);
    }
}
